[package]
name = "rusty-chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pyo3 = "0.18.3"
regex = "1.7.3"


[lib]
name = "chess_model"
crate-type = ["cdylib"]
